name: taby
description: Tabu game.
publish_to: "none"
version: 1.0.1+5

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  provider: ^6.0.4

  # Database
  hive_flutter: ^1.1.0

  # Google
  google_mobile_ads: ^2.3.0

  # Utitilities
  kartal: ^2.4.3
  auto_size_text: ^3.0.0
  vibration: ^1.7.6
  audioplayers: ^3.0.1
  video_player: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/data/words.json
    - assets/data/sound/
    - assets/data/video/
    - assets/icon/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Light.ttf
          weight: 300
        - asset: assets/fonts/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Prompt-SemiBold.ttf
          weight: 600
    - family: Merienda
      fonts:
        - asset: assets/fonts/Merienda-Regular.ttf
        - asset: assets/fonts/Merienda-Bold.ttf
          weight: 700
